/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fgroupindonesia.frames.client;

/**
 *
 * @author asus
 */
public class QuestionFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form QuestionFrame
     */
    public QuestionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonSoalSebelumnya = new javax.swing.JButton();
        buttonSoalSelanjutnya = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelWaktuTersisa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelSoal = new javax.swing.JPanel();
        panelSoalMode1_PGText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        radioButtonSoalMode1_PG_A1 = new javax.swing.JRadioButton();
        radioButtonSoalMode1_PG_B1 = new javax.swing.JRadioButton();
        radioButtonSoalMode1_PG_C1 = new javax.swing.JRadioButton();
        radioButtonSoalMode1_PG_D1 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelSoalText_PGGambar = new javax.swing.JPanel();
        panelSoalText_Essay = new javax.swing.JPanel();
        panelSoalVideo_PGText = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelNomorSoal = new javax.swing.JLabel();
        labelTotalSoal = new javax.swing.JLabel();

        setTitle("Mulai Mengerjakan Soal");

        jPanel1.setPreferredSize(new java.awt.Dimension(394, 50));

        buttonSoalSebelumnya.setText("Sebelumnya <<");
        jPanel1.add(buttonSoalSebelumnya);

        buttonSoalSelanjutnya.setText(">> Selanjutnya");
        jPanel1.add(buttonSoalSelanjutnya);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        labelWaktuTersisa.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelWaktuTersisa.setText("Waktu Tersisa 00:00");
        jPanel3.add(labelWaktuTersisa);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        panelSoal.setPreferredSize(new java.awt.Dimension(394, 200));
        panelSoal.setLayout(new java.awt.CardLayout());

        panelSoalMode1_PGText.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(123, 100));

        jTextArea1.setBackground(java.awt.SystemColor.control);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        panelSoalMode1_PGText.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pilihan Ganda"));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(4, 1));

        radioButtonSoalMode1_PG_A1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonSoalMode1_PG_A1.setText("Pilihan A");
        jPanel8.add(radioButtonSoalMode1_PG_A1);

        radioButtonSoalMode1_PG_B1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonSoalMode1_PG_B1.setText("Pilihan B");
        jPanel8.add(radioButtonSoalMode1_PG_B1);

        radioButtonSoalMode1_PG_C1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonSoalMode1_PG_C1.setText("Pilihan C");
        jPanel8.add(radioButtonSoalMode1_PG_C1);

        radioButtonSoalMode1_PG_D1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonSoalMode1_PG_D1.setText("Pilihan D");
        jPanel8.add(radioButtonSoalMode1_PG_D1);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel6.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("A.");
        jPanel6.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("B.");
        jPanel6.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("C.");
        jPanel6.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("D.");
        jPanel6.add(jLabel4);

        jPanel5.add(jPanel6, java.awt.BorderLayout.WEST);

        panelSoalMode1_PGText.add(jPanel5, java.awt.BorderLayout.CENTER);

        panelSoal.add(panelSoalMode1_PGText, "card2");

        javax.swing.GroupLayout panelSoalText_PGGambarLayout = new javax.swing.GroupLayout(panelSoalText_PGGambar);
        panelSoalText_PGGambar.setLayout(panelSoalText_PGGambarLayout);
        panelSoalText_PGGambarLayout.setHorizontalGroup(
            panelSoalText_PGGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panelSoalText_PGGambarLayout.setVerticalGroup(
            panelSoalText_PGGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        panelSoal.add(panelSoalText_PGGambar, "card3");

        javax.swing.GroupLayout panelSoalText_EssayLayout = new javax.swing.GroupLayout(panelSoalText_Essay);
        panelSoalText_Essay.setLayout(panelSoalText_EssayLayout);
        panelSoalText_EssayLayout.setHorizontalGroup(
            panelSoalText_EssayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panelSoalText_EssayLayout.setVerticalGroup(
            panelSoalText_EssayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        panelSoal.add(panelSoalText_Essay, "card4");

        javax.swing.GroupLayout panelSoalVideo_PGTextLayout = new javax.swing.GroupLayout(panelSoalVideo_PGText);
        panelSoalVideo_PGText.setLayout(panelSoalVideo_PGTextLayout);
        panelSoalVideo_PGTextLayout.setHorizontalGroup(
            panelSoalVideo_PGTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        panelSoalVideo_PGTextLayout.setVerticalGroup(
            panelSoalVideo_PGTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        panelSoal.add(panelSoalVideo_PGText, "card5");

        jPanel2.add(panelSoal, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        labelNomorSoal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNomorSoal.setText("Nomor Soal : xx");
        labelNomorSoal.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 1));
        jPanel4.add(labelNomorSoal);

        labelTotalSoal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalSoal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalSoal.setText("Total Soal : xx");
        labelTotalSoal.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 20));
        jPanel4.add(labelTotalSoal);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSoalSebelumnya;
    private javax.swing.JButton buttonSoalSelanjutnya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelNomorSoal;
    private javax.swing.JLabel labelTotalSoal;
    private javax.swing.JLabel labelWaktuTersisa;
    private javax.swing.JPanel panelSoal;
    private javax.swing.JPanel panelSoalMode1_PGText;
    private javax.swing.JPanel panelSoalText_Essay;
    private javax.swing.JPanel panelSoalText_PGGambar;
    private javax.swing.JPanel panelSoalVideo_PGText;
    private javax.swing.JRadioButton radioButtonSoalMode1_PG_A1;
    private javax.swing.JRadioButton radioButtonSoalMode1_PG_B1;
    private javax.swing.JRadioButton radioButtonSoalMode1_PG_C1;
    private javax.swing.JRadioButton radioButtonSoalMode1_PG_D1;
    // End of variables declaration//GEN-END:variables
}
