package fgroupindonesia.frames;

import fgroupindonesia.data.History;
import fgroupindonesia.data.User;
import fgroupindonesia.frames.MainFrame;
import fgroupindonesia.helper.DBConnection;
import fgroupindonesia.helper.TableRenderer;
import java.util.ArrayList;

/**
 *
 * @author asus
 */
public class HistoryFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistoryFrame
     */
    public HistoryFrame() {
        initComponents();
        db = new DBConnection();
        refresh();
    }

    public HistoryFrame(User dataPerson) {
        initComponents();
        db = new DBConnection();
        dataUser = dataPerson;
        refresh();
    }

    User dataUser;
    DBConnection db;
    MainFrame mframe;
    ArrayList<History> list;
    TableRenderer tableRender;

    public void setUser(User dataIn) {
        dataUser = dataIn;
    }

    public void setMainFrameReference(MainFrame mf) {
        mframe = mf;
    }

    public void refresh() {
        db.connect();
        if (dataUser != null) {
            list = db.select_history_all(dataUser.getUsername());
        } else {
            list = db.select_history_all();
        }

        tableRender = new TableRenderer();
        tableRender.render_history(tableDataManagement, list);
        labelTotalData.setText("Total Data : " + list.size());

    }

    public void clearAll() {
        db.delete_history_all();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataManagement = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        buttonClearAll = new javax.swing.JButton();
        labelTotalData = new javax.swing.JLabel();

        setTitle("Riwayat");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tableDataManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "username", "jenis", "description", "tanggal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDataManagement);
        if (tableDataManagement.getColumnModel().getColumnCount() > 0) {
            tableDataManagement.getColumnModel().getColumn(0).setMinWidth(0);
            tableDataManagement.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableDataManagement.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(403, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/search.png"))); // NOI18N
        buttonSearch.setText("Search");
        jPanel1.add(buttonSearch);

        buttonClearAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/clear.png"))); // NOI18N
        buttonClearAll.setText("Clear All");
        jPanel1.add(buttonClearAll);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        labelTotalData.setText("Total Data : x");
        getContentPane().add(labelTotalData, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        mframe.displayMenuManagement();
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClearAll;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTotalData;
    private javax.swing.JTable tableDataManagement;
    // End of variables declaration//GEN-END:variables
}
