package fgroupindonesia.frames;

/**
 *
 * @author asus
 */
public class MenuManagementFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuManagementFrame
     */
    public MenuManagementFrame() {
        initComponents();
    }

    MainFrame mframe;

    public void setMainFrameReference(MainFrame mf) {
        mframe = mf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonManagementStudent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        buttonManagementSoal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        buttonManagementJawaban = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        buttonManagementKategori = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        buttonManagementImbalan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        buttonHistory = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setTitle("Menu Management");
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel1.setLayout(new java.awt.BorderLayout());

        buttonManagementStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/users.png"))); // NOI18N
        buttonManagementStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagementStudentActionPerformed(evt);
            }
        });
        jPanel1.add(buttonManagementStudent, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Siswa");
        jPanel1.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel7.setLayout(new java.awt.BorderLayout());

        buttonManagementSoal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/doc.png"))); // NOI18N
        buttonManagementSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagementSoalActionPerformed(evt);
            }
        });
        jPanel7.add(buttonManagementSoal, java.awt.BorderLayout.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Soal");
        jPanel7.add(jLabel10, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel8.setLayout(new java.awt.BorderLayout());

        buttonManagementJawaban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/checklist.png"))); // NOI18N
        buttonManagementJawaban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagementJawabanActionPerformed(evt);
            }
        });
        jPanel8.add(buttonManagementJawaban, java.awt.BorderLayout.CENTER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jawaban");
        jPanel8.add(jLabel11, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel9.setLayout(new java.awt.BorderLayout());

        buttonManagementKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/file.png"))); // NOI18N
        buttonManagementKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagementKategoriActionPerformed(evt);
            }
        });
        jPanel9.add(buttonManagementKategori, java.awt.BorderLayout.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Kategori");
        jPanel9.add(jLabel12, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel9);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel10.setLayout(new java.awt.BorderLayout());

        buttonManagementImbalan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/medal.png"))); // NOI18N
        buttonManagementImbalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManagementImbalanActionPerformed(evt);
            }
        });
        jPanel10.add(buttonManagementImbalan, java.awt.BorderLayout.CENTER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Imbalan");
        jPanel10.add(jLabel13, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel11.setLayout(new java.awt.BorderLayout());

        buttonHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/time.png"))); // NOI18N
        buttonHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHistoryActionPerformed(evt);
            }
        });
        jPanel11.add(buttonHistory, java.awt.BorderLayout.CENTER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Riwayat");
        jPanel11.add(jLabel14, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel11);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonManagementStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagementStudentActionPerformed

        mframe.displayManagementStudent();
        this.dispose();
        
    }//GEN-LAST:event_buttonManagementStudentActionPerformed

    private void buttonManagementSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagementSoalActionPerformed

        mframe.displayManagementQuestion();
        this.dispose();
        
    }//GEN-LAST:event_buttonManagementSoalActionPerformed

    private void buttonManagementJawabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagementJawabanActionPerformed

        mframe.displayManagementAnswerQuestion();
        this.dispose();
        
    }//GEN-LAST:event_buttonManagementJawabanActionPerformed

    private void buttonManagementKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagementKategoriActionPerformed

        mframe.displayManagementCategory();
        this.dispose();
    }//GEN-LAST:event_buttonManagementKategoriActionPerformed

    private void buttonManagementImbalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManagementImbalanActionPerformed

        mframe.displayManagementRewards();
        this.dispose();
        
    }//GEN-LAST:event_buttonManagementImbalanActionPerformed

    private void buttonHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHistoryActionPerformed

        mframe.displayHistory();
        this.dispose();
        
    }//GEN-LAST:event_buttonHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHistory;
    private javax.swing.JButton buttonManagementImbalan;
    private javax.swing.JButton buttonManagementJawaban;
    private javax.swing.JButton buttonManagementKategori;
    private javax.swing.JButton buttonManagementSoal;
    private javax.swing.JButton buttonManagementStudent;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
