/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fgroupindonesia.frames;

/**
 *
 * @author asus
 */
public class MenuActivityFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuActivityFrame
     */
    public MenuActivityFrame() {
        initComponents();
    }

    MainFrame mframe;

    public void setMainFrameReference(MainFrame mf) {
        mframe = mf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonOpenQuestion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonOpenRewards = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonOpenAdditionalQuestion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonOpenHistory = new javax.swing.JButton();

        setTitle("Menu Aktifitas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soal Terkini");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        buttonOpenQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/write.png"))); // NOI18N
        buttonOpenQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenQuestionActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOpenQuestion, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Melihat Imbalan");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        buttonOpenRewards.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/medal.png"))); // NOI18N
        buttonOpenRewards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenRewardsActionPerformed(evt);
            }
        });
        jPanel2.add(buttonOpenRewards, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Minta Soal Tambahan");
        jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        buttonOpenAdditionalQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/write_add.png"))); // NOI18N
        jPanel3.add(buttonOpenAdditionalQuestion, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 15, 20, 15));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Check Riwayat");
        jPanel4.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        buttonOpenHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fgroupindonesia/images/time.png"))); // NOI18N
        buttonOpenHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenHistoryActionPerformed(evt);
            }
        });
        jPanel4.add(buttonOpenHistory, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed


    }//GEN-LAST:event_formInternalFrameClosed

    private void buttonOpenRewardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenRewardsActionPerformed

        mframe.displayMenuRewards();
        this.dispose();

    }//GEN-LAST:event_buttonOpenRewardsActionPerformed

    private void buttonOpenHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenHistoryActionPerformed

        mframe.displayHistory();
        this.dispose();
    }//GEN-LAST:event_buttonOpenHistoryActionPerformed

    private void buttonOpenQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenQuestionActionPerformed
        mframe.displayStartQuestion();
    }//GEN-LAST:event_buttonOpenQuestionActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        mframe.logout();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOpenAdditionalQuestion;
    private javax.swing.JButton buttonOpenHistory;
    private javax.swing.JButton buttonOpenQuestion;
    private javax.swing.JButton buttonOpenRewards;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
